services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-actions-runner
    env_file:
      - .env
    environment:
      - GH_OWNER=${GH_OWNER}
      - GH_TOKEN=${GH_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-runner-${HOSTNAME}}
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_REPOS_PATH:-~/repositories}:/home/runner/repositories
      - ${RUNNER_DATA:-./runner-data}:/home/runner/_work
    restart: unless-stopped
    networks:
      - runner-network
    privileged: true  # Required for Docker-in-Docker operations

networks:
  runner-network:
    driver: bridge

volumes:
  runner-data:
    driver: local
